/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_airpost_relan_quirky_Zbar */

#ifndef _Included_net_airpost_relan_quirky_Zbar
#define _Included_net_airpost_relan_quirky_Zbar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_airpost_relan_quirky_Zbar
 * Method:    process
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_airpost_relan_quirky_Zbar_process
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
